sms_checkin/urls.py
from django.conf.urls import url
from django.contrib import admin

from events.views import EventListView, EventDetailView
from reminders.views import incoming_message

urlpatterns = [
    url(r'^$', EventListView.as_view(), name='home'),
    url(r'^event/(?P<pk>[0-9]+)/$', EventDetailView.as_view(), name='view_event'),
    url(r'^sms/message/$', incoming_message),
    url(r'^admin/', admin.site.urls),
]
admin.site.site_header = 'Affinity SMS Admin'

events/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.db.models import Avg, Count
from django.db import models
from django.utils import timezone

from timezone_field import TimeZoneField
from phonenumber_field.modelfields import PhoneNumberField

from reminders.models import Prompt

class Event(models.Model):
    name = models.CharField(max_length=150)
    location = models.CharField(max_length=150, null=True)
    host_name = models.CharField(max_length=150, null=True)

    time_zone = TimeZoneField(default='US/Pacific')
    starts_at = models.DateTimeField(verbose_name="Starts at (local)")
    ends_at = models.DateTimeField(verbose_name="Ends at (local)")
    
    created = models.DateTimeField(auto_now_add=True)

    prompt_before = models.ForeignKey(Prompt, related_name='+', null=True)
    prompt_after = models.ForeignKey(Prompt, related_name='+', null=True)

    def __str__(self):
        return 'Event #{0} - {1}'.format(self.pk, self.name)

    def get_absolute_url(self):
        return reverse('view_event', args=[str(self.id)])

    @property
    def participants(self):
        return [a.participant for a in self.attendance_set.select_related('participant')]

    @property
    def confirmed(self):
        return self.attendance_set.filter(confirmed=True)

    @property
    def ratings(self):
        return self.attendance_set.filter(rating__isnull=False).annotate(Count('id')).aggregate(Avg('rating'))

    def get_starts_at(self):
        """Returns event.starts_at in specified event.time_zone"""
        # NOTE: don't just force timezone into datetime
        # DST will mess it up, http://bugs.python.org/issue22994
        # use time_zone.localize and normalize instead

        # clear existing tzinfo (which was UTC from server), making a naive datetime
        starts_at_naive = self.starts_at.replace(tzinfo=None)
        # use timezone.localize to add the user's correct tzinfo
        starts_at_local = self.time_zone.localize(starts_at_naive)
        # normalize to apply DST rules
        starts_at_normal = self.time_zone.normalize(starts_at_local)
        return starts_at_normal
    get_starts_at.short_description = "Starts at (%s)" % timezone.get_current_timezone_name()
    # this displays in django admin, which converts to server time before display

    def get_ends_at(self):
        """Returns event.ends_at in specified event.time_zone"""
        ends_at_naive = self.ends_at.replace(tzinfo=None)
        ends_at_local = self.time_zone.localize(ends_at_naive)
        ends_at_normal = self.time_zone.normalize(ends_at_local)
        return ends_at_normal
    get_ends_at.short_description = "Ends at (%s)" % timezone.get_current_timezone_name()


class Participant(models.Model):
    created = models.DateTimeField(auto_now_add=True)

    name = models.CharField(max_length=150)
    phone = PhoneNumberField()
    email = models.EmailField()

    event = models.ManyToManyField(Event, through='Attendance')
    
    def __str__(self):
        return 'Participant #{0} - {1}'.format(self.pk, self.name)

    @property
    def attending(self):
        """ all attendances for a participant, ordered by event end times descending """
        future_attendances = self.attendance_set.select_related('event')
        # TODO filter out attendances in the past #.filter(event__ends_at__gte=timezone.now())
        return future_attendances.order_by('-event__ends_at')

class Attendance(models.Model):
    participant = models.ForeignKey(Participant)
    event = models.ForeignKey(Event)
    confirmed = models.NullBooleanField(default=None, blank=True, null=True)
    rating = models.IntegerField(default=None, blank=True, null=True)

    class Meta:
        verbose_name_plural = "attending"

reminders/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
import django_q

from django.template import Template, Context


class Prompt(models.Model):
    minutes_offset = models.IntegerField()
    name = models.CharField(max_length=32)
    message = models.TextField()

    def __str__(self):
        return 'Prompt #{0} - {1}'.format(self.pk, self.name)

    def render(self, attendance):
        t = Template(self.message)
        c = Context({
                        'event': attendance.event,
                        'participant': attendance.participant
                    })
        return t.render(c)

class Message(models.Model):
    to_participant = models.ForeignKey('events.Participant') # use string to avoid circular imports
    body = models.TextField()
    sent_at = models.DateTimeField()
    status = models.CharField(max_length=32)

events/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.generic import DetailView
from django.views.generic.list import ListView

from .models import Event

class EventListView(ListView):
    model = Event

class EventDetailView(DetailView):
    model = Event

reminders/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from twilio import twiml
from twilio.twiml.messaging_response import MessagingResponse

from django.shortcuts import render

from events.models import Participant
from messages.decorators import twilio_view
from messages.requests import decompose
from messages.parsers import ParseMessage


@twilio_view
def incoming_message(request):
    r = MessagingResponse()
    twilio_request = decompose(request)
    message = ParseMessage(twilio_request.body)

    # get participant from phone number
    try:
        participant = Participant.objects.get(phone=twilio_request.from_)
    except Participant.DoesNotExist:
        r.message("You do not seem to be signed up to use this system. Please contact info@affinity.works")
        return r
    except Participant.MultipleObjectsReturned:
        # pick the most recently created
        participant = Participant.objects.filter(phone=twilio_request.from_).order_by('-created')[0]

    if not participant.attending:
        r.message("Sorry, you do not seem to be attending any upcoming events.")
        return r
    else:
        attendance = participant.attending[0]

    if not attendance.confirmed:
        # check in
        if message.is_yes():
            attendance.confirmed = True
            attendance.save()
            r.message("Thanks for checking in to %s!" % attendance.event.name)
            return r
        elif message.is_no():
            attendance.confirmed = False
            attendance.save()
            r.message("Sorry you won't be able to make it to %s." % attendance.event.name)
            return r
        else:
            r.message("Please reply with just Y or N.")
            return r

    else:
        if not attendance.rating:
            # rate event
            if message.is_number():
                attendance.rating = int(message.body)
                attendance.save()
                r.message("Thanks for rating the event.")
                return r
            else:
                r.message("Please reply with a number 1-3 rating the event.")
                return r
        else:
            if message.is_reset():
                attendance.rating = None
                attendance.save()
                r.message("Your rating is reset. Please reply with a number 1-3 rating the event.")
                return r
            else:
                r.message("We're all done. If you'd like to reset your event rating, reply RESET.")
                return r
    return r

templates/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %} - SMS CheckIn</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- CSS -->
    {% bootstrap_css %}
    <link href="{% static 'sms_checkin/css/base.css' %}" rel="stylesheet">

    {% block page_css %}{% endblock %}
  </head>

  <body>

    <div class="container">
      <!-- matching affinity.works styles, but FYI these probably should be inside the page content -->
      <p class="notice"></p>
      <p class="alert"></p>


      <div class="page-header">
      <div class="row">
        <div class="col-10">
          <h2>
            <a href="/" class="affinity-logo"><img src="{% static 'sms_checkin/images/affinity-logo.svg' %}" width="300"></a>
            <small> Affinity </small>
          </h2>
        </div>

        <div class="col-2 text-right">
          <div class="dropdown">
            {% if request.user.is_authenticated %}
            <a class="btn btn-secondary dropdown-toggle" href="/" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <img src="{% static 'sms_checkin/images/jane_doe.jpg' %}">
              <span>
              {% if request.user.first_name or request.user.last_name%}
                  {{ request.user.first_name }} {{ request.user.last_name }}
              {%else %}
                {{ request.user.username }}
              {%endif%}
              </span>
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="/admin">Admin</a>
              <a class="dropdown-item" href="/admin/logout">Logout</a>
            </div>
            {% else %}
            <a class="btn btn-secondary" href="/admin">
              <span> Log In  </span>
            </a>
            {% endif %}
          </div>
        </div>
      </div>
      <br>
      </div>

      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{ message }}
        </div>
        {% endfor %}
      {% endif %}

      {% block nav %}{% endblock %}

      {% block content %}{% endblock content %}

    </div> <!-- /container -->

<!--     <footer class="sticky">
      <div class="container">
        <p class="text-muted">&copy; Affinity Works 2017</p>
      </div>
    </footer> -->

    <!-- JavaScript -->
    {% bootstrap_javascript jquery=1 %}

    {% block page_js %}{% endblock %}

  </body>

</html>

templates/events/event_detail.html
{% extends "events/events_base.html" %}

{% block title %}{{ event }}{% endblock title %}

{% block content %}
  <div class="list-group-item">
    <div class="col-xs-12 col-md-8">
      <a href="{{event.get_absolute_url}}">{{ event.name }}</a> {%if event.location%}</a>at {{event.location}}{%endif%} {% if event.host_name %} hosted by {{event.host_name}}{%endif%}
    </div>

    <div class="col-xs-6 col-md-2">
      <span class="label label-info">&check;</span> {{ event.participant_set.count }} RSVPs
    </div>
    
    {% if request.user.is_authenticated%}
    <div class="col-xs-6 col-md-2">
      <span class="label label-info">&bigstar;</span> {{ event.ratings.rating__avg|floatformat| default:'?' }} Rating
    </div>
    {%endif%}
  </div>

    <div class="container">
      {% if request.user.is_authenticated %}
        <div class="list-group">
          {% for attendance in event.attendance_set.all %}
            <div class="list-group-item">
              <div class="col-md-8 col-8">
                <div class="row">{{attendance.participant.name}}</div>
                <div class="row"><small>{{attendance.participant.email}}, {{attendance.participant.phone}}</small></div>
              </div>
              <div class="col-xs-4 col-md-3 col-lg-2">
                <div class="btn-group" role="group">
                  <button type="button" class="btn btn-{%if attendance.confirmed == True%}success{%else%}secondary{%endif%}">Y</button>
                  <button type="button" class="btn btn-{%if attendance.confirmed == None%}warning{%else%}secondary{%endif%}">?</button>
                  <button type="button" class="btn btn-{%if attendance.confirmed == False%}danger{%else%}secondary{%endif%}">N</button>
                </div>
              </div>
              <div class="col-xs-4 col-md-1">
                <div class="btn-group">
                  <button type="button" class="btn btn-secondary {%if attendance.rating%}active{%endif%}">{{attendance.rating | default:'?' }}</button>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      {% else %}
      <div class="row">
        <div class="col-6">
          <div class="jumbotron">
            <div class="jumbotron-contents">
              <h1>{{ event.confirmed.count | default:0 }}</h1>
              <h2>Confirmed</h2>
            </div>
          </div>
        </div>

        <div class="col-6">
          <div class="jumbotron">
            <div class="jumbotron-contents">
              <h1>{{ event.ratings.rating__avg|floatformat | default:'?' }}</h1>
              <h2>Rating</h2>
            </div>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/events/event_list.html
{% extends "events/events_base.html" %}

{% block title %}Event Attendance{% endblock title %}

{% block content %}
  <div class="list-group">

      {% if not object_list %}
        <p><strong>No upcoming events.</strong>
      {% endif %}

      <div class="list-group-item">
      {% for event in object_list %}
        <div class="col-8"><a href="{{ event.get_absolute_url }}">{{ event.name }}</a> {%if event.location%}at {{event.location}}{%endif%} {% if event.host_name %} hosted by {{event.host_name}}{%endif%}
        <br> {{ event.starts_at }} - {{ event.ends_at }} ({{ event.time_zone }})</div>
        <div class="col-2"><span class="label label-info">&check;</span> {{ event.attendance_set.count }} RSVPs</div>
        <div class="col-2"><a href="{{ event.get_absolute_url }}" class="btn btn-primary">View RSVPs</a></div>
        </tr>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/events/events_base.html
{% extends "base.html" %}

{%block nav %}
<div><ul class="nav nav-tabs"><li class="nav-item"><a class="nav-link active" href="/">Events Attendance</a></li></ul><br></div>
{% endblock %}